version: '3.8'
services:
  redis-db:
#    hostname: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - redis-caching-network
  mysql-db:
    image: mysql
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-scripts.sql:/docker-entrypoint-initdb.d/mysql-scripts.sql
    networks:
      - redis-caching-network
  redis-caching:
    image: redis-app
    depends_on:
      - redis-db
      - mysql-db
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "/wait && java -jar redis-app.jar"
    environment:
      - WAIT_HOSTS=mysql-db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=10
      - WAIT_HOST_CONNECT_TIMEOUT=30
    ports:
      - "8081:8081"
    networks:
      - redis-caching-network
    links:
      - redis-db:redis
networks:
  redis-caching-network:
    driver: bridge